### ISSUE TITLE
Unresolved PdfiumDocumentWrapperQt symbol when launching QtCreator

### ISSUE THREAD

**Issue by nocnokneo** [erdinc09/MarkdownEditView#7]
When launching Qt Creator I get a pop-up with the message:

```
/home/tbraunjones/.local/share/data/QtProject/qtcreator/plugins/5.0.0/libMarkdownEditView.so: Cannot load library /home/tbraunjones/.local/share/data/QtProject/qtcreator/plugins/5.0.0/libMarkdownEditView.so: (/usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5: undefined symbol: _ZN15QtWebEngineCore23PdfiumDocumentWrapperQtC1EPKvmRK5QSizePKc, version Qt_5)
```
Looks like libMarkDownEditView is expecting an overload the the `PdfiumDocumentWrapperQt` constructor with a `QSize` argument that does not exist in `libQt5WebEngineWidgets.so.5.15.2`

```
$ c++filt '_ZN15QtWebEngineCore23PdfiumDocumentWrapperQtC1EPKvmRK5QSizePKc'
QtWebEngineCore::PdfiumDocumentWrapperQt::PdfiumDocumentWrapperQt(void const*, unsigned long, QSize const&, char const*)
$ nm --demangle ~/Qt/Tools/QtCreator/lib/Qt/lib/libQt5WebEngineWidgets.so.5.15.2 | grep PdfiumDocumentWrapperQt::PdfiumDocumentWrapperQt
                 U QtWebEngineCore::PdfiumDocumentWrapperQt::PdfiumDocumentWrapperQt(void const*, unsigned long, char const*)@@Qt_5
```

**Comment by erdinc09** [comment]
Threre was a linking problem, I should have tested the release. Sorry for that. (I switched to the gold linker in linux)

Can you please try the new version [1.5.0](https://github.com/erdinc09/MarkdownEditView/releases/tag/1.5.0) . I also changed the version numbering strategy.

**Comment by nocnokneo** [comment]
Thanks for looking into this. Unfortunately, I still get the same error message with version 1.5.0.

**Comment by nocnokneo** [comment]
Nevermind - it _does_ work now! Thanks.

**Comment by nocnokneo** [comment]
(The solution was to launch Qt Creator from qtcreator.sh which augments `LD_LIBRARY_PATH` to find the bundled Qt libraries under `<QtCreatorInstallDir>/lib/Qt/lib`)
